Repository krishnasaurabh/expertiza, pull requests merged in 2022-03, with the labels that each got.

#5 split db_query method, change method names
  app/controllers/reputation_web_service_controller.rb
Labels: enhancement

#3 Split json_generator, db_query methods, changed param to list
  app/controllers/reputation_web_service_controller.rb
  spec/controllers/reputation_web_service_controller_spec.rb
Labels: enhancement

#8 Updated the calculate_peer_review_grade method
  app/controllers/reputation_web_service_controller.rb
Labels: enhancement

#9 Updating variables instances
  app/controllers/reputation_web_service_controller.rb
  app/views/reputation_web_service/client.html.erb
Labels: enhancement

#15 Fix bugs in views, and comment encryption
  app/controllers/reputation_web_service_controller.rb
  app/views/reputation_web_service/client.html.erb
Labels: bug, enhancement

#17 Used constants instead of url strings
  app/controllers/reputation_web_service_controller.rb
Labels: enhancement

#19 fixed failing test cases for client method
  app/controllers/reputation_web_service_controller.rb
  app/views/reputation_web_service/client.html.erb
Labels: bug

#20 Changes for code comments and fixes for views
  app/controllers/reputation_web_service_controller.rb
  app/views/reputation_web_service/client.html.erb
Labels: documentation, enhancement

#21 review comments fix
  app/controllers/reputation_web_service_controller.rb
  spec/controllers/reputation_web_service_controller_spec.rb
Labels: bug

#22 Fix typo reqest to request
  app/controllers/reputation_web_service_controller.rb
Labels: bug
